# Generated by Django 4.2.6 on 2023-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Areas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('assessment_area_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('award_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=38)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('school_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('assessment_area_id', models.IntegerField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('correct_answer_id', models.IntegerField()),
                ('sydney_participants', models.IntegerField()),
                ('student_score', models.DecimalField(decimal_places=3, max_digits=10)),
                ('participant', models.IntegerField()),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sydney_percentile', models.IntegerField()),
                ('award_id', models.IntegerField()),
                ('year_level_name', models.CharField(max_length=100)),
            ],
        ),
    ]
